
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DISETOP.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CATEGORIA_PROYECTOS
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CATEGORIA_PROYECTOS()
    {

        this.COSTO_PROYECTOS = new HashSet<COSTO_PROYECTOS>();

        this.PROYECTOS = new HashSet<PROYECTO>();

    }


    public string CODIGO_CATEGORIA { get; set; }

    public string NOMBRE_CATEGORIA { get; set; }

    public string COMENTARIO { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<COSTO_PROYECTOS> COSTO_PROYECTOS { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PROYECTO> PROYECTOS { get; set; }

}

}
