//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DISETOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORIA_PROYECTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATEGORIA_PROYECTOS()
        {
            this.COSTO_PROYECTOS = new HashSet<COSTO_PROYECTOS>();
            this.PROYECTOS = new HashSet<PROYECTO>();
        }
    
        public string CODIGO_CATEGORIA { get; set; }
        public string NOMBRE_CATEGORIA { get; set; }
        public string COMENTARIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COSTO_PROYECTOS> COSTO_PROYECTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROYECTO> PROYECTOS { get; set; }
    }
}
