//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DISETOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COSTO_PROYECTOS
    {
        public string CODIGO_COSTO_PROYECTO { get; set; }
        public string FK_CODIGO_PROYECTO { get; set; }
        public string FK_CODIGO_CATEGORIA { get; set; }
        public Nullable<decimal> DIA_TRABAJADOR { get; set; }
        public Nullable<decimal> COMBUSTIBLE { get; set; }
        public Nullable<decimal> VIATICOS { get; set; }
        public Nullable<decimal> HOSPEDAJE { get; set; }
        public Nullable<decimal> TIMBRES_CERTIFICACIONES { get; set; }
        public Nullable<decimal> MATERIALES { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public string COMENTARIO { get; set; }
    
        public virtual CATEGORIA_PROYECTOS CATEGORIA_PROYECTOS { get; set; }
        public virtual PROYECTO PROYECTO { get; set; }
    }
}
