//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DISETOP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DISETOPEntities : DbContext
    {
        public DISETOPEntities()
            : base("name=DISETOPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACTIVO> ACTIVOS { get; set; }
        public virtual DbSet<CATEGORIA_PROYECTOS> CATEGORIA_PROYECTOS { get; set; }
        public virtual DbSet<COSTO_PROYECTOS> COSTO_PROYECTOS { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADOS { get; set; }
        public virtual DbSet<PAGO> PAGOS { get; set; }
        public virtual DbSet<PROYECTO> PROYECTOS { get; set; }
        public virtual DbSet<USUARIO> USUARIOS { get; set; }
    
        public virtual int sp_ActualizaEmpleados(string codigo_empleado, Nullable<int> cedula, string nombre_empleado, Nullable<int> telefono, string correo, string direccion, string comentario)
        {
            var codigo_empleadoParameter = codigo_empleado != null ?
                new ObjectParameter("codigo_empleado", codigo_empleado) :
                new ObjectParameter("codigo_empleado", typeof(string));
    
            var cedulaParameter = cedula.HasValue ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(int));
    
            var nombre_empleadoParameter = nombre_empleado != null ?
                new ObjectParameter("nombre_empleado", nombre_empleado) :
                new ObjectParameter("nombre_empleado", typeof(string));
    
            var telefonoParameter = telefono.HasValue ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(int));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            var comentarioParameter = comentario != null ?
                new ObjectParameter("comentario", comentario) :
                new ObjectParameter("comentario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ActualizaEmpleados", codigo_empleadoParameter, cedulaParameter, nombre_empleadoParameter, telefonoParameter, correoParameter, direccionParameter, comentarioParameter);
        }
    
        public virtual int sp_EditarActivos(string codigoActivo, string nombre_de_activo, string numero_de_serie, Nullable<System.DateTime> fecha_de_compra, string proveedor, Nullable<decimal> valor_de_compra, Nullable<decimal> valor_actual, string comentario)
        {
            var codigoActivoParameter = codigoActivo != null ?
                new ObjectParameter("CodigoActivo", codigoActivo) :
                new ObjectParameter("CodigoActivo", typeof(string));
    
            var nombre_de_activoParameter = nombre_de_activo != null ?
                new ObjectParameter("Nombre_de_activo", nombre_de_activo) :
                new ObjectParameter("Nombre_de_activo", typeof(string));
    
            var numero_de_serieParameter = numero_de_serie != null ?
                new ObjectParameter("Numero_de_serie", numero_de_serie) :
                new ObjectParameter("Numero_de_serie", typeof(string));
    
            var fecha_de_compraParameter = fecha_de_compra.HasValue ?
                new ObjectParameter("Fecha_de_compra", fecha_de_compra) :
                new ObjectParameter("Fecha_de_compra", typeof(System.DateTime));
    
            var proveedorParameter = proveedor != null ?
                new ObjectParameter("Proveedor", proveedor) :
                new ObjectParameter("Proveedor", typeof(string));
    
            var valor_de_compraParameter = valor_de_compra.HasValue ?
                new ObjectParameter("Valor_de_compra", valor_de_compra) :
                new ObjectParameter("Valor_de_compra", typeof(decimal));
    
            var valor_actualParameter = valor_actual.HasValue ?
                new ObjectParameter("Valor_actual", valor_actual) :
                new ObjectParameter("Valor_actual", typeof(decimal));
    
            var comentarioParameter = comentario != null ?
                new ObjectParameter("Comentario", comentario) :
                new ObjectParameter("Comentario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EditarActivos", codigoActivoParameter, nombre_de_activoParameter, numero_de_serieParameter, fecha_de_compraParameter, proveedorParameter, valor_de_compraParameter, valor_actualParameter, comentarioParameter);
        }
    
        public virtual int sp_EditarPagos(string codigoPago, string fK_CodigoEmpleado, string cuentaBancaria, string diasAPagar, Nullable<decimal> monto, Nullable<System.DateTime> fechaDePago, string comentario)
        {
            var codigoPagoParameter = codigoPago != null ?
                new ObjectParameter("CodigoPago", codigoPago) :
                new ObjectParameter("CodigoPago", typeof(string));
    
            var fK_CodigoEmpleadoParameter = fK_CodigoEmpleado != null ?
                new ObjectParameter("FK_CodigoEmpleado", fK_CodigoEmpleado) :
                new ObjectParameter("FK_CodigoEmpleado", typeof(string));
    
            var cuentaBancariaParameter = cuentaBancaria != null ?
                new ObjectParameter("CuentaBancaria", cuentaBancaria) :
                new ObjectParameter("CuentaBancaria", typeof(string));
    
            var diasAPagarParameter = diasAPagar != null ?
                new ObjectParameter("DiasAPagar", diasAPagar) :
                new ObjectParameter("DiasAPagar", typeof(string));
    
            var montoParameter = monto.HasValue ?
                new ObjectParameter("Monto", monto) :
                new ObjectParameter("Monto", typeof(decimal));
    
            var fechaDePagoParameter = fechaDePago.HasValue ?
                new ObjectParameter("FechaDePago", fechaDePago) :
                new ObjectParameter("FechaDePago", typeof(System.DateTime));
    
            var comentarioParameter = comentario != null ?
                new ObjectParameter("Comentario", comentario) :
                new ObjectParameter("Comentario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EditarPagos", codigoPagoParameter, fK_CodigoEmpleadoParameter, cuentaBancariaParameter, diasAPagarParameter, montoParameter, fechaDePagoParameter, comentarioParameter);
        }
    
        public virtual int sp_EliminaActivos(string codigo_activo)
        {
            var codigo_activoParameter = codigo_activo != null ?
                new ObjectParameter("codigo_activo", codigo_activo) :
                new ObjectParameter("codigo_activo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaActivos", codigo_activoParameter);
        }
    
        public virtual int sp_EliminaEmpleados(string codigo_empleado)
        {
            var codigo_empleadoParameter = codigo_empleado != null ?
                new ObjectParameter("codigo_empleado", codigo_empleado) :
                new ObjectParameter("codigo_empleado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaEmpleados", codigo_empleadoParameter);
        }
    
        public virtual int sp_EliminaPagos(string codigoPago)
        {
            var codigoPagoParameter = codigoPago != null ?
                new ObjectParameter("CodigoPago", codigoPago) :
                new ObjectParameter("CodigoPago", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaPagos", codigoPagoParameter);
        }
    
        public virtual int sp_InsertaActivos(string codigo_activo, string nombre_de_activo, string numero_de_serie, Nullable<System.DateTime> fechaDeCompra, string proveedor, Nullable<decimal> valor_de_compra, Nullable<decimal> valor_actual, string comentario)
        {
            var codigo_activoParameter = codigo_activo != null ?
                new ObjectParameter("codigo_activo", codigo_activo) :
                new ObjectParameter("codigo_activo", typeof(string));
    
            var nombre_de_activoParameter = nombre_de_activo != null ?
                new ObjectParameter("nombre_de_activo", nombre_de_activo) :
                new ObjectParameter("nombre_de_activo", typeof(string));
    
            var numero_de_serieParameter = numero_de_serie != null ?
                new ObjectParameter("numero_de_serie", numero_de_serie) :
                new ObjectParameter("numero_de_serie", typeof(string));
    
            var fechaDeCompraParameter = fechaDeCompra.HasValue ?
                new ObjectParameter("FechaDeCompra", fechaDeCompra) :
                new ObjectParameter("FechaDeCompra", typeof(System.DateTime));
    
            var proveedorParameter = proveedor != null ?
                new ObjectParameter("Proveedor", proveedor) :
                new ObjectParameter("Proveedor", typeof(string));
    
            var valor_de_compraParameter = valor_de_compra.HasValue ?
                new ObjectParameter("Valor_de_compra", valor_de_compra) :
                new ObjectParameter("Valor_de_compra", typeof(decimal));
    
            var valor_actualParameter = valor_actual.HasValue ?
                new ObjectParameter("Valor_actual", valor_actual) :
                new ObjectParameter("Valor_actual", typeof(decimal));
    
            var comentarioParameter = comentario != null ?
                new ObjectParameter("comentario", comentario) :
                new ObjectParameter("comentario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaActivos", codigo_activoParameter, nombre_de_activoParameter, numero_de_serieParameter, fechaDeCompraParameter, proveedorParameter, valor_de_compraParameter, valor_actualParameter, comentarioParameter);
        }
    
        public virtual int sp_InsertaEmpleados(string codigo_empleado, Nullable<int> cedula, string nombre_empleado, Nullable<int> telefono, string correo, string direccion, string comentario)
        {
            var codigo_empleadoParameter = codigo_empleado != null ?
                new ObjectParameter("codigo_empleado", codigo_empleado) :
                new ObjectParameter("codigo_empleado", typeof(string));
    
            var cedulaParameter = cedula.HasValue ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(int));
    
            var nombre_empleadoParameter = nombre_empleado != null ?
                new ObjectParameter("nombre_empleado", nombre_empleado) :
                new ObjectParameter("nombre_empleado", typeof(string));
    
            var telefonoParameter = telefono.HasValue ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(int));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            var comentarioParameter = comentario != null ?
                new ObjectParameter("comentario", comentario) :
                new ObjectParameter("comentario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaEmpleados", codigo_empleadoParameter, cedulaParameter, nombre_empleadoParameter, telefonoParameter, correoParameter, direccionParameter, comentarioParameter);
        }
    
        public virtual int sp_InsertarPagoEmpleado(string codigoPago, string fK_CodigoEmpleado, string cuentaBancaria, string diasAPagar, Nullable<decimal> monto, Nullable<System.DateTime> fechaDePago, string comentario)
        {
            var codigoPagoParameter = codigoPago != null ?
                new ObjectParameter("CodigoPago", codigoPago) :
                new ObjectParameter("CodigoPago", typeof(string));
    
            var fK_CodigoEmpleadoParameter = fK_CodigoEmpleado != null ?
                new ObjectParameter("FK_CodigoEmpleado", fK_CodigoEmpleado) :
                new ObjectParameter("FK_CodigoEmpleado", typeof(string));
    
            var cuentaBancariaParameter = cuentaBancaria != null ?
                new ObjectParameter("CuentaBancaria", cuentaBancaria) :
                new ObjectParameter("CuentaBancaria", typeof(string));
    
            var diasAPagarParameter = diasAPagar != null ?
                new ObjectParameter("DiasAPagar", diasAPagar) :
                new ObjectParameter("DiasAPagar", typeof(string));
    
            var montoParameter = monto.HasValue ?
                new ObjectParameter("Monto", monto) :
                new ObjectParameter("Monto", typeof(decimal));
    
            var fechaDePagoParameter = fechaDePago.HasValue ?
                new ObjectParameter("FechaDePago", fechaDePago) :
                new ObjectParameter("FechaDePago", typeof(System.DateTime));
    
            var comentarioParameter = comentario != null ?
                new ObjectParameter("Comentario", comentario) :
                new ObjectParameter("Comentario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertarPagoEmpleado", codigoPagoParameter, fK_CodigoEmpleadoParameter, cuentaBancariaParameter, diasAPagarParameter, montoParameter, fechaDePagoParameter, comentarioParameter);
        }
    
        public virtual int sp_RegistrarUsuario(string usuario, string contrasena, ObjectParameter registrado, ObjectParameter mensaje)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("Contrasena", contrasena) :
                new ObjectParameter("Contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RegistrarUsuario", usuarioParameter, contrasenaParameter, registrado, mensaje);
        }
    
        public virtual ObjectResult<sp_RetornaActivos_Result> sp_RetornaActivos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaActivos_Result>("sp_RetornaActivos");
        }
    
        public virtual ObjectResult<sp_RetornaActivosPorID_Result> sp_RetornaActivosPorID(string codigo_activo)
        {
            var codigo_activoParameter = codigo_activo != null ?
                new ObjectParameter("codigo_activo", codigo_activo) :
                new ObjectParameter("codigo_activo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaActivosPorID_Result>("sp_RetornaActivosPorID", codigo_activoParameter);
        }
    
        public virtual ObjectResult<sp_RetornaEmpleados_Result> sp_RetornaEmpleados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaEmpleados_Result>("sp_RetornaEmpleados");
        }
    
        public virtual ObjectResult<sp_RetornaEmpleadosPorID_Result> sp_RetornaEmpleadosPorID(string codigo_empleado)
        {
            var codigo_empleadoParameter = codigo_empleado != null ?
                new ObjectParameter("codigo_empleado", codigo_empleado) :
                new ObjectParameter("codigo_empleado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaEmpleadosPorID_Result>("sp_RetornaEmpleadosPorID", codigo_empleadoParameter);
        }
    
        public virtual ObjectResult<sp_RetornaPagos_Result> sp_RetornaPagos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaPagos_Result>("sp_RetornaPagos");
        }
    
        public virtual ObjectResult<sp_RetornaPagosPorID_Result> sp_RetornaPagosPorID(string codigoPago)
        {
            var codigoPagoParameter = codigoPago != null ?
                new ObjectParameter("CodigoPago", codigoPago) :
                new ObjectParameter("CodigoPago", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaPagosPorID_Result>("sp_RetornaPagosPorID", codigoPagoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_ValidarUsuario(string usuario, string contrasena)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("Contrasena", contrasena) :
                new ObjectParameter("Contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_ValidarUsuario", usuarioParameter, contrasenaParameter);
        }
    }
}
