
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DISETOP.Models
{

using System;
    using System.Collections.Generic;
    
public partial class EMPLEADO
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public EMPLEADO()
    {

        this.PAGOS = new HashSet<PAGO>();

    }


    public string CODIGO_EMPLEADO { get; set; }

    public Nullable<int> CEDULA { get; set; }

    public string NOMBRE_EMPLEADO { get; set; }

    public Nullable<int> TELEFONO { get; set; }

    public string CORREO { get; set; }

    public string DIRECCION { get; set; }

    public string COMENTARIO { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PAGO> PAGOS { get; set; }

}

}
