//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DISETOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROYECTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROYECTO()
        {
            this.COSTO_PROYECTOS = new HashSet<COSTO_PROYECTOS>();
        }
    
        public string CODIGO_PROYECTO { get; set; }
        public string NOMBRE_PROYECTO { get; set; }
        public string FK_CODIGO_CATEGORIA { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO { get; set; }
        public string ESTADO { get; set; }
        public Nullable<System.DateTime> FECHA_FIN { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public string COMENTARIO { get; set; }
    
        public virtual CATEGORIA_PROYECTOS CATEGORIA_PROYECTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COSTO_PROYECTOS> COSTO_PROYECTOS { get; set; }
    }
}
